[project]
name = "compare"
version = "0.1.0"
description = "Comparison tool for Rizin to other RE frameworks."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.4.2",
    "pathlib>=1.0.1",
    "prettytable>=3.17.0",
    "pyelftools>=0.32",
    "ruff>=0.15.4",
    "rzpipe",
    "typing>=3.10.0.0",
]

[tool.uv.sources]
rzpipe = { path = "rz-pipe/python" }
