.Dd Mar 10, 2017
.Dt RZ-DOCKER 1
.Sh NAME
.Nm rz-docker
.Nd Open files within an rizin contained in a Docker image
.Sh SYNOPSIS
.Nm rz-docker
.Op Fl s
.Op Fl u
.Op Fl l
.Op Fl r
.Op Fl d
.Ar file
.Sh DESCRIPTION
rizin is a commandline hexadecimal editor, and this tool allows you to create a contained version inside a Docker image to open your files safely.
.Pp
The options are:
.Bl -tag -width Fl
.It Fl s
open shell inside the docker image (user rizin, pass rizin)
.It Fl d
debug program (only for linux-x86-32/64)
.It Fl u
update or create the docker image with rizin inside
.It Fl l
List all docker images with rizin
.It Fl r
Remove the rizin docker image
.Sh SEE ALSO
.Pp
.Xr rizin(1)
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>
