.Dd Mar 31, 2020
.Dt RZ_TEST 1
.Sh NAME
.Nm rz-test
.Nd rizin regression testsuite
.Sh SYNOPSIS
.Nm rz-test
.Op Fl h
.Op Fl i
.Op Fl n
.Op Fl q
.Op Fl v
.Op Fl V
.Op Fl j Ar threads
.Op Fl r Ar rz-path
.Op Fl m Ar rz-asm-pth
.Op Fl f Ar bin-for-json-tests
.Op Fl C Ar chdir
.Op [test-(dir|file) ...]
.Sh DESCRIPTION
Run all the rizin-regressions tests matching a specific word in the name.
.Pp
You need rizin to be available in $PATH.
.Sh OPTIONS
.Bl -tag -width Fl
.It Fl h
Show the help/usage message
.It Fl i
Interactive mode
.It Fl n
Do not run any test, just load/parse them
.It Fl q
Quiet mode (use like this: rz-test -qv)
.It Fl v
Show version number
.It Fl V
Be verbose
.It Fl j Ar threads
Specify the number of tasks to run in parallel
.It Fl r Ar rz-path
Set path to rizin executable
.It Fl n Ar rz-asm-path
Set path to rz-asmexecutable
.It Fl m Ar rz-asm-path
Set path to rz-asmexecutable
.It Fl f Ar bin-for-json-tests
Load the given binary when running the JSON tests
.It Fl C Ar directory
Early chdir before running any test
.El
.Sh USAGE
.Pp
Use the -n flag to dont run any test. Just load them.
.Pp
  $ rz-test -n
  [rz-test] Loading tests...
.Pp
.Sh SEE ALSO
.Pp
.Xr rizin(1) ,
.Xr rz-hash(1) ,
.Xr rz-find(1) ,
.Xr rz-bin(1) ,
.Xr rz-find(1) ,
.Xr rz-diff(1) ,
.Xr rz-asm(1) ,
.Sh AUTHORS
.Pp
Written by pancake <pancake@nopcode.org>.
