# SPDX-FileCopyrightText: 2018 Simos Xenitellis
# SPDX-License-Identifier: LGPL-3.0-only

name: rizin
version: '0.7.3'
base: core18
summary: Rizin reverse engineering framework and tool
description: |
  Rizin is a complete framework for reverse-engineering
  and analyzing binaries; composed of a set of small utilities
  that can be used together or independently from the command line.
  Built around a disassembler for computer software which generates
  assembly language source code from machine-executable code,
  it supports a variety of executable formats for different processors
  and operating systems.

grade: devel # Development version, can only publish to beta/candidate channels.
confinement: devmode # Unrestricted access, only to beta/candidate channels.

# rizin requires in most cases privileged access to resources.
# The following "plugs" are thus superfluous because the "devmode" confinement
# gives full access to the system as if it were a DEB/RPM package.
# With the following plugs though, and the "strict" confinement, rizin
# would be able to do things like editing an executable file in the $HOME folder.

apps:
  rizin:
    command: usr/bin/rizin
    plugs: [home]
  rz-find:
    command: usr/bin/rz-find
    plugs: [home]
  rz-hash:
    command: usr/bin/rz-hash
    plugs: [home]
  rz-asm:
    command: usr/bin/rz-asm
    plugs: [home]
  rz-bin:
    command: usr/bin/rz-bin
    plugs: [home]
  rz-diff:
    command: usr/bin/rz-diff
    plugs: [home]
  rz-gg:
    command: usr/bin/rz-gg
    plugs: [home]
  rz-run:
    command: usr/bin/rz-run
    plugs: [home]
  rz-ax:
    command: usr/bin/rz-ax
    plugs: [home]
  rz-sign:
    command: usr/bin/rz-sign
    plugs: [home]

parts:
  rizin:
    source: https://github.com/rizinorg/rizin.git
    source-tag: '0.7.3'
    plugin: meson
    meson-parameters: [--prefix=/usr]
    override-build: |
      pip3 install --system meson
      snapcraftctl build
    build-packages:
      - python3-pip
      - python3-setuptools
      - libmagic-dev
      - pkg-config
      - libzip-dev
      - liblz4-dev
      - libssl-dev
      - libbsd-dev
      - libcapstone-dev
