include ../config.mk

NAME=rz_main

OBJS+=main.o
OBJS+=rz_ax.o
OBJS+=rz_asm.o
OBJS+=rz_gg.o
OBJS+=rz_run.o
OBJS+=rz_bin.o
OBJS+=rz_sign.o
OBJS+=rz_find.o
OBJS+=rz_agent.o
OBJS+=rz_diff.o
OBJS+=rizin.o
OBJS+=rz_hash.o

# See MAIN_LINK_ALL
include deps.mk

include ../rules.mk
