// SPDX-FileCopyrightText: 2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only

// Generated with sys/gen_il_reg_idx_mapping_from_reg_profile.py
static const RzILGlobalIdxMapEntry global_idx[] = {
	{ "cg", 0 },
	{ "pc", 1 },
	{ "r10", 2 },
	{ "r11", 3 },
	{ "r12", 4 },
	{ "r13", 5 },
	{ "r14", 6 },
	{ "r15", 7 },
	{ "r4", 8 },
	{ "r5", 9 },
	{ "r6", 10 },
	{ "r7", 11 },
	{ "r8", 12 },
	{ "r9", 13 },
	{ "sp", 14 },
	{ "sr", 15 },
};
