// SPDX-FileCopyrightText: 2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only

static const RzILGlobalIdxMapEntry global_idx[] = {
	{ "ccr", 0 },
	{ "e0", 1 },
	{ "e1", 2 },
	{ "e2", 3 },
	{ "e3", 4 },
	{ "e4", 5 },
	{ "e5", 6 },
	{ "e6", 7 },
	{ "e7", 8 },
	{ "r0", 9 },
	{ "r1", 10 },
	{ "r2", 11 },
	{ "r3", 12 },
	{ "r4", 13 },
	{ "r5", 14 },
	{ "r6", 15 },
	{ "r7", 16 },
};
