# SPDX-FileCopyrightText: 2026 Rot127 <rot127@posteo.com>
# SPDX-License-Identifier: LGPL-3.0-only

[binaries]
c       = '<<path-to-toolchain>>/bin/mips64-linux-musl-gcc'
cpp     = '<<path-to-toolchain>>/bin/mips64-linux-musl-g++'
ar      = '<<path-to-toolchain>>/bin/mips64-linux-musl-ar'
as      = '<<path-to-toolchain>>/bin/mips64-linux-musl-as'
ranlib  = '<<path-to-toolchain>>/bin/mips64-linux-musl-ranlib'
ld      = '<<path-to-toolchain>>/bin/mips64-linux-musl-ld'
strip   = '<<path-to-toolchain>>/bin/mips64-linux-musl-strip'
pkgconfig = 'false'

[properties]
sys_root = '<<path-to-toolchain>>/mips64-linux-musl'

[built-in options]
c_args = [ '--sysroot=<<path-to-toolchain>>/mips64-linux-musl' ]
c_link_args = [ '--sysroot=<<path-to-toolchain>>/mips64-linux-musl' ]

[host_machine]
system = 'linux'
cpu_family = 'mips64'
cpu = 'mips64'
endian = 'big'
