# SPDX-FileCopyrightText: 2024-2026 moste00 <ubermenchun@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause
[binaries]
c       = 'riscv64-linux-gnu-gcc'
cpp     = 'riscv64-linux-gnu-g++'
ar      = 'riscv64-linux-gnu-ar'
as      = 'riscv64-linux-gnu-as'
ranlib  = 'riscv64-linux-gnu-ranlib'
ld      = 'riscv64-linux-gnu-ld'
strip   = 'riscv64-linux-gnu-strip'

[host_machine]
system = 'linux'
cpu_family = 'riscv64'
cpu = 'riscv64'
endian = 'little'

[properties]
sys_root = '/usr/riscv64-linux-gnu'