# SPDX-FileCopyrightText: 2024-2026 moste00 <ubermenchun@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause
# Replace (manually or with sed -i) <<path-to-bootlin-installation>> with the actual path to your Bootlin directory
# (The Bootlin directory is the parent of bin/riscv32-buildroot-linux-musl-*)
[binaries]
c       = 'riscv32-buildroot-linux-musl-gcc'
cpp     = 'riscv32-buildroot-linux-musl-g++'
ar      = 'riscv32-buildroot-linux-musl-ar'
strip   = 'riscv32-buildroot-linux-musl-strip'
objcopy = 'riscv32-buildroot-linux-musl-objcopy'
objdump = 'riscv32-buildroot-linux-musl-objdump'
ranlib  = 'riscv32-buildroot-linux-musl-ranlib'
pkgconfig = 'pkg-config'

[built-in options]
c_args      = ['-march=rv32gc', '-mabi=ilp32d', '-static', '-fPIC']
cpp_args    = ['-march=rv32gc', '-mabi=ilp32d', '-static', '-fPIC']
c_link_args   = ['-march=rv32gc', '-mabi=ilp32d', '-fPIC']
cpp_link_args = ['-march=rv32gc', '-mabi=ilp32d', '-fPIC']
default_library = 'static'

[properties]
sys_root        = '<<path-to-bootlin-installation>>/riscv32-buildroot-linux-musl/sysroot'
pkg_config_libdir = '<<path-to-bootlin-installation>>/riscv32-buildroot-linux-musl/sysroot/usr/lib/pkgconfig'

[host_machine]
system     = 'linux'
cpu_family = 'riscv32'
cpu        = 'riscv32'
endian     = 'little'