#include "maps.h"

struct rl78_instr rl78_instr_maps[4 * 256] = {
        // map 0
        // 0x000-0x0f
        [0x000] = { .operation = RL78_OPERATION_NOP },
        [0x001] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDW },
        [0x002] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_ADDW },
        [0x003] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDW },
        [0x004] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_ADDW },
        [0x005] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDW },
        [0x006] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDW },
        [0x007] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDW },
        [0x008] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },
        [0x009] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x00A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_ADD },
        [0x00B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x00C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_ADD },
        [0x00D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_ADD },
        [0x00E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_ADD },
        [0x00F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_ADD },

        // 0x010-0x01f
        [0x010] = { { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_ADDW },
        [0x012] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x013] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x014] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x015] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x016] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x017] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x018] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x019] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x01A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_ADDC },
        [0x01B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x01C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_ADDC },
        [0x01D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_ADDC },
        [0x01E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_ADDC },
        [0x01F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_ADDC },

        // 0x020-0x02f
        [0x020] = { { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_SUBW },
        [0x022] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_SUBW },
        [0x023] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBW },
        [0x024] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_SUBW },
        [0x025] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBW },
        [0x026] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBW },
        [0x027] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBW },
        [0x028] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x029] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x02A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_SUB },
        [0x02B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x02C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_SUB },
        [0x02D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_SUB },
        [0x02E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_SUB },
        [0x02F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_SUB },

        // 0x030-0x03f
        [0x030] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x032] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x033] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCHW },
        [0x034] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x035] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCHW },
        [0x036] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x037] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCHW },
        [0x038] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x039] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x03A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_SUBC },
        [0x03B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x03C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_SUBC },
        [0x03D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_SUBC },
        [0x03E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_SUBC },
        [0x03F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_SUBC },

        // 0x040-0x04f
        [0x040] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_CMP },
        [0x041] = { { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x042] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_CMPW },
        [0x043] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMPW },
        [0x044] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_CMPW },
        [0x045] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMPW },
        [0x046] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMPW },
        [0x047] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMPW },
        [0x048] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x049] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x04A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_CMP },
        [0x04B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x04C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_CMP },
        [0x04D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CMP },
        [0x04E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_CMP },
        [0x04F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                        { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                        .operation = RL78_OPERATION_CMP },

        // 0x050-0x05f
        [0x050] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x051] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x052] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x053] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x054] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x055] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x056] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x057] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x058] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x059] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x05A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_AND },
        [0x05B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x05C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_AND },
        [0x05D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_AND },
        [0x05E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_AND },
        [0x05F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                        { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                        .operation = RL78_OPERATION_AND },

        // 0x060-0x06f
        [0x060] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x062] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x063] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x064] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x065] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x066] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x067] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x068] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x069] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x06A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_OR },
        [0x06B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x06C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_OR },
        [0x06D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_OR },
        [0x06E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_OR },
        [0x06F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_OR },

        // 0x070-0x07f
        [0x070] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x072] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x073] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x074] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x075] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x076] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x077] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x078] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x079] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x07A] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_XOR },
        [0x07B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x07C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    {.type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_XOR },
        [0x07D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_XOR },
        [0x07E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_XOR },
        [0x07F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_XOR },

        // 0x080-0x08f
        [0x080] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x081] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x082] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x083] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x084] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x085] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x086] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x087] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x088] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x089] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x08A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x08B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x08C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_MOV },
        [0x08D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x08E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x08F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOV },

        // 0x090-0x09f
        [0x090] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x091] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x092] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x093] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x094] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x095] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x096] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x097] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x098] = { { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x099] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x09A] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x09B] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x09C] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x09D] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x09E] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x09F] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },

        // 0x0A0-0x0af
        [0x0a0] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_INC },
        [0x0a1] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INCW },
        [0x0a2] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_INCW },
        [0x0a3] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INCW },
        [0x0a4] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INC },
        [0x0a5] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INCW },
        [0x0a6] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INCW },
        [0x0a7] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_INCW },
        [0x0a8] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x0a9] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x0aA] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x0aB] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x0aC] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_MOVW },
        [0x0aD] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0aE] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0aF] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOVW },

        // 0x0B0-0x0bf
        [0x0b0] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_DEC },
        [0x0b1] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DECW },
        [0x0b2] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_DECW },
        [0x0b3] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DECW },
        [0x0b4] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DEC },
        [0x0b5] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DECW },
        [0x0b6] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DECW },
        [0x0b7] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_DECW },
        [0x0b8] = { { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0b9] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0bA] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0bB] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0bC] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0bD] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0bE] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0bF] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                    { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },

        // 0x0C0-0x0cf
        [0x0c0] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_POP },
        [0x0c1] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_PUSH },
        [0x0c2] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_POP },
        [0x0c3] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_PUSH },
        [0x0c4] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_POP },
        [0x0c5] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_PUSH },
        [0x0c6] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_POP },
        [0x0c7] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_PUSH },
        [0x0c8] = { { .v0 = RL78_CR_SP, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x0c9] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x0cA] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x0cB] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x0cC] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x0cD] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x0cE] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },
        [0x0cF] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                    { .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                   .operation = RL78_OPERATION_MOV },

        // 0x0D0-0x0df
        [0x0d0] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP0 },
        [0x0d1] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP0 },
        [0x0d2] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP0 },
        [0x0d3] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP0 },
        [0x0d4] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP0 },
        [0x0d5] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_CMP0 },
        [0x0d6] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MULU },
        [0x0d7] = { .operation = RL78_OPERATION_RET },
        [0x0d8] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x0d9] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOV },
        [0x0dA] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0dB] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x0dC] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BC },
        [0x0dD] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BZ },
        [0x0dE] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BNC },
        [0x0dF] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BNZ },

        // 0x0E0-0x0ef
        [0x0e0] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEB },
        [0x0e1] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEB },
        [0x0e2] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEB },
        [0x0e3] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEB },
        [0x0e4] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEB },
        [0x0e5] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_ONEB },
        [0x0e6] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEW },
        [0x0e7] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ONEW },
        [0x0e8] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x0e9] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOV },
        [0x0eA] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0eB] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x0eC] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_20 },
                   .operation = RL78_OPERATION_BR },
        [0x0eD] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_BR },
        [0x0eE] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_16 },
                   .operation = RL78_OPERATION_BR },
        [0x0eF] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BR },

        // 0x0F0-0x0ff
        [0x0f0] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRB },
        [0x0f1] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRB },
        [0x0f2] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRB },
        [0x0f3] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRB },
        [0x0f4] = { { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRB },
        [0x0f5] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_CLRB },
        [0x0f6] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRW },
        [0x0f7] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CLRW },
        [0x0f8] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOV },
        [0x0f9] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOV },
        [0x0fA] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_MOVW },
        [0x0fB] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_MOVW },
        [0x0fC] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_20 },
                   .operation = RL78_OPERATION_CALL },
        [0x0fD] = { { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                   .operation = RL78_OPERATION_CALL },
        [0x0fE] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_16 },
                   .operation = RL78_OPERATION_CALL },

        // map 1
        // 0x100-0x10f
        [0x100] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x101] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x102] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x103] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x104] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x105] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x106] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x107] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x108] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x109] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_ADDW },
        [0x10A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x10B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x10C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x10D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x10E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },
        [0x10F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADD },

        // 0x110-0x11f
        [0x110] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x111] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x112] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x113] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x114] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x115] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x116] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x117] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x118] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x11A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x11B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x11C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x11D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x11E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },
        [0x11F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_ADDC },

        // 0x120-0x12f
        [0x120] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x121] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x122] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x123] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x124] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x125] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x126] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x127] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x128] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x129] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_SUBW },
        [0x12A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x12B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x12C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x12D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x12E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },
        [0x12F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUB },

        // 0x130-0x13f
        [0x130] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x131] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x132] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x133] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x134] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x135] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x136] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x137] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x138] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x13A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x13B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x13C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x13D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x13E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },
        [0x13F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_SUBC },

        // 0x140-0x14f
        [0x140] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x141] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x142] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x143] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x144] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x145] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x146] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x147] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x148] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x149] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_CMPW },
        [0x14A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x14B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x14C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x14D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x14E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },
        [0x14F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_CMP },

        // 0x150-0x15f
        [0x150] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x151] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x152] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x153] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x154] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x155] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x156] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x157] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x158] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x159] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_INC },
        [0x15A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x15B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x15C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x15D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x15E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },
        [0x15F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_AND },

        // 0x160-0x16f
        [0x160] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x161] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x162] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x163] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x164] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x165] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x166] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x167] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x168] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x169] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_DEC },
        [0x16A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x16B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x16C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x16D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x16E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },
        [0x16F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_OR },

        // 0x170-0x17f
        [0x170] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x171] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x172] = { { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x173] = { { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x174] = { { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x175] = { { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x176] = { { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x177] = { { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x178] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x179] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_INCW },
        [0x17A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x17B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x17C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x17D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x17E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },
        [0x17F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XOR },

        // 0x180-0x18f
        [0x180] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_ADD },
        [0x182] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_ADD },
        [0x184] = { { .v0 = 0x0080, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x185] = { { .v0 = 0x0090, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x186] = { { .v0 = 0x00A0, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x187] = { { .v0 = 0x00B0, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x189] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                   .operation = RL78_OPERATION_DECW },
        [0x18A] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },
        [0x18B] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },
        [0x18C] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_E, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },
        [0x18D] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_D, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },
        [0x18E] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_L, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },
        [0x18F] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_H, .type = RL78_OPERAND_TYPE_SYMBOL },
                   .operation = RL78_OPERATION_XCH },

        // 0x190-0x19f
        [0x190] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_ADDC },
        [0x192] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_ADDC },
        [0x194] = { { .v0 = 0x0082, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x195] = { { .v0 = 0x0092, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x196] = { { .v0 = 0x00A2, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x197] = { { .v0 = 0x00B2, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },

        // 0x1a0-0x1af
        [0x1a0] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_SUB },
        [0x1a2] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_SUB },
        [0x1a4] = { { .v0 = 0x0084, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1a5] = { { .v0 = 0x0094, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1a6] = { { .v0 = 0x00A4, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1a7] = { { .v0 = 0x00B4, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1a8] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_XCH },
        [0x1a9] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                    .operation = RL78_OPERATION_XCH },
        [0x1aa] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_ABSOLUTE_ADDR_16 },
                    .operation = RL78_OPERATION_XCH },
        [0x1ab] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_XCH },
        [0x1ac] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    .operation = RL78_OPERATION_XCH },
        [0x1ad] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    .operation = RL78_OPERATION_XCH },
        [0x1ae] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                    .operation = RL78_OPERATION_XCH },
        [0x1af] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    .operation = RL78_OPERATION_XCH },

        // 0x1b0-0x1bf
        [0x1b0] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_SUBC },
        [0x1b2] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_SUBC },
        [0x1b4] = { { .v0 = 0x0086, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1b5] = { { .v0 = 0x0096, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1b6] = { { .v0 = 0x00A6, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1b7] = { { .v0 = 0x00B6, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1b8] = { { .v0 = RL78_SFR_ES, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_MOV },
        [0x1b9] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                    .operation = RL78_OPERATION_XCH },

        // 0x1c0-0x1cf
        [0x1c0] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_CMP },
        [0x1c2] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_CMP },
        [0x1c3] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BH },
        [0x1c4] = { { .v0 = 0x0088, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1c5] = { { .v0 = 0x0098, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1c6] = { { .v0 = 0x00A8, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1c7] = { { .v0 = 0x00B8, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1c8] = { .operation = RL78_OPERATION_SKC },
        [0x1c9] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                    .operation = RL78_OPERATION_MOV },
        [0x1ca] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_CALL },
        [0x1cb] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_BR },
        [0x1cc] = { .operation = RL78_OPERATION_BRK },
        [0x1cd] = { { .v0 = RL78_SFR_PSW, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_POP },
        [0x1ce] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_MOVS },
        [0x1cf] = { { .v0 = RL78_RB_RB0, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_SEL },

        // 0x1d0-0x1df
        [0x1d0] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_AND },
        [0x1d2] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_AND },
        [0x1d3] = { { .type = RL78_OPERAND_TYPE_RELATIVE_ADDR_8 },
                   .operation = RL78_OPERATION_BNH },
        [0x1d4] = { { .v0 = 0x008A, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1d5] = { { .v0 = 0x009A, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1d6] = { { .v0 = 0x00AA, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1d7] = { { .v0 = 0x00BA, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1d8] = { .operation = RL78_OPERATION_SKNC },
        [0x1d9] = { { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_MOV },
        [0x1da] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_CALL },
        [0x1db] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = 1, .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                    .operation = RL78_OPERATION_ROR },
        [0x1dc] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = 1, .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                    .operation = RL78_OPERATION_ROLC },
        [0x1dd] = { { .v0 = RL78_SFR_PSW, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_PUSH },
        [0x1de] = { { .v0 = RL78_GPR_X, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_BASED_ADDR },
                    .operation = RL78_OPERATION_CMPS },
        [0x1df] = { { .v0 = RL78_RB_RB1, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_SEL },

        // 0x1e0-0x1ef
        [0x1e0] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_OR },
        [0x1e2] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_OR },
        [0x1e3] = { .operation = RL78_OPERATION_SKH },
        [0x1e4] = { { .v0 = 0x008C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1e5] = { { .v0 = 0x009C, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1e6] = { { .v0 = 0x00AC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1e7] = { { .v0 = 0x00BC, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1e8] = { .operation = RL78_OPERATION_SKZ },
        [0x1e9] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                    .operation = RL78_OPERATION_MOV },
        [0x1ea] = { { .v0 = RL78_GPR_DE, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_CALL },
        [0x1eb] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = 1, .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                    .operation = RL78_OPERATION_ROL },
        [0x1ec] = { .operation = RL78_OPERATION_RETB },
        [0x1ed] = { .operation = RL78_OPERATION_HALT },
        [0x1ee] = { { .v0 = RL78_GPR_AX, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = 1, .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                    .operation = RL78_OPERATION_ROLWC },
        [0x1ef] = { { .v0 = RL78_RB_RB2, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_SEL },


        // 0x1f0-0x1ff
        [0x1f0] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_B, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_XOR },
        [0x1f2] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                   .operation = RL78_OPERATION_XOR },
        [0x1f3] = { .operation = RL78_OPERATION_SKNH },
        [0x1f4] = { { .v0 = 0x008E, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1f5] = { { .v0 = 0x009E, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1f6] = { { .v0 = 0x00AE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1f7] = { { .v0 = 0x00BE, .type = RL78_OPERAND_TYPE_INDIRECT_ADDR },
                   .operation = RL78_OPERATION_CALLT },
        [0x1f8] = { .operation = RL78_OPERATION_SKNZ },
        [0x1f9] = { { .v0 = RL78_GPR_HL, .v1 = RL78_GPR_C, .type = RL78_OPERAND_TYPE_BASED_INDEX_ADDR },
                    { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_MOV },
        [0x1fa] = { { .v0 = RL78_GPR_HL, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_CALL },
        [0x1fb] = { { .v0 = RL78_GPR_A, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = 1, .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                    .operation = RL78_OPERATION_RORC },
        [0x1fc] = { .operation = RL78_OPERATION_RETI },
        [0x1fd] = { .operation = RL78_OPERATION_STOP },
        [0x1fe] = { { .v0 = RL78_GPR_BC, .type = RL78_OPERAND_TYPE_SYMBOL },
                    { .v0 = 1, .type = RL78_OPERAND_TYPE_IMMEDIATE_8 },
                    .operation = RL78_OPERATION_ROLWC },
        [0x1ff] = { { .v0 = RL78_RB_RB3, .type = RL78_OPERAND_TYPE_SYMBOL },
                    .operation = RL78_OPERATION_SEL },
};
