.Dd Jul 28, 2016
.Dt RZ_AGENT 1
.Sh NAME
.Nm RZ_AGENT
.Nd rizin remoting manager TODO
.Sh SYNOPSIS
.Nm rz-agent
.Op Fl adhs
.Op Fl p Ar PORT
.Sh DESCRIPTION
Spawn a server... TODO
.Bl -tag -width Fl
.It Fl a, Cm all
Listen for everyone (localhost by default)
.It Fl d, Cm daemon
Run in daemon mode
.It Fl h, Cm help
Show help prompt
.It Fl u, Cm httpauth
Enable HTTP Authentification support
.It Fl t, Cm httpauthfile
user:password authentification file
.It Fl p, Cm port Ar PORT
Specify listening port for the agent
.It Fl v
Show version information
.El
.Sh EXAMPLES
.Pp
TODO
.Sh SEE ALSO
.Pp
.Xr rizin(1)
