.Dd Jan 24, 2024
.Dt RZ_AX 1
.Sh NAME
.Nm rz-ax
.Nd rizin base converter
.Sh SYNOPSIS
.Nm rz-ax
.Op Fl abBdefFhiIkLlNnorsStuvwxC
.Op [expr] ...
.Sh DESCRIPTION
This command is part of the rizin project.
.Pp
This command allows you to convert values between positive and negative integers, floats, octal, binary, ternary, and hexadecimal values.
.Sh OPTIONS
.Bl -tag -width Fl
.It Fl l
Append newline to output (for -E/-D/-r/..)
.It Fl a
Show ASCII table
.It Fl b
Convert from binary string to character (rz-ax -b 01000101 01110110)
.It Fl B
Convert from string to binary (rz-ax -B hello)
.It Fl d
Force output as integer (rz-ax -d 3 outputs 3 instead of 0x3)
.It Fl e
Swap endian.
.It Fl f
Floating point arithmetic (rz-ax -f 6.3+2.1)
.It Fl F
Read C strings from stdin and output in hex pairs. Useful to load shellcodes
.It Fl h
Show usage help message
.It Fl i
Dump as C byte array
.It Fl I
Convert LONG to/from IP ADDRESS
.It Fl k
Keep the same base as the input data
.It Fl L
Convert binary to hexadecimal (rz-ax -L 111111111 outputs 0x1ff)
.It Fl n
Show binary number from integer value
.It Fl N
Show binary C string from integer value
.It Fl o
Convert from octal string to char (rz-ax -o \162 \172)
.It Fl r
Rizin style output
.It Fl s
Convert from hex string to character (rz-ax -s 43 4a 50)
.It Fl S
Convert from character to hex string (rz-ax -S < /bin/ls > ls.hex)
.It Fl t
Convert timestamp to string (rz-ax -t 1234567890)
.It Fl u
Convert given value to human-readable units format
.It Fl v
Show version number
.It Fl w
Convert signed word (16-bit) (rz-ax -w 16 0xffff)
.It Fl x
Hash string
.It Fl p
Show position of set bits in the binary representation (rz-ax -p 0xb3)
.El
.Sh USAGE
.Pp
Force output mode (numeric base)
.Pp
=f floating point
=2 binary
=3 ternary
=8 octal
=10 decimal
=16 hexadecimal
.Pp
Available variable types are:
.Pp
int -> hex rz-ax 10,
hex -> int rz-ax 0xa,
-int -> hex rz-ax -77,
-hex -> int rz-ax 0xffffffb3,
int -> bin rz-ax b30,
int -> ternary rz-ax t42,
ternary -> int rz-ax 1010dt,
bin -> int rz-ax 1010d,
float -> hex rz-ax 3.33f,
hex -> float rz-ax Fx40551ed8,
oct -> hex rz-ax 35o,
hex -> oct rz-ax Ox12 (O is a letter),
hex -> bin rz-ax Bx63,
bin -> hex rz-ax 1100011b,
ternary -> hex rz-ax 212t,
hex ->ternary rz-ax Tx23,
raw -> hex rz-ax -S < /binfile,
hex -> raw rz-ax -s 414141,
.Sh SEE ALSO
.Pp
.Xr rizin(1) ,
.Xr rz-hash(1) ,
.Xr rz-find(1) ,
.Xr rz-bin(1) ,
.Xr rz-diff(1) ,
.Xr rz-gg(1) ,
.Xr rz-run(1) ,
.Xr rz-asm(1)
.Sh AUTHORS
.Pp
Written by pancake pancake@nopcode.org.
.Pp
byteninjaa0.