.Dd Aug 25, 2023
.Dt RZ_DIFF 1
.Sh NAME
.Nm RZ_DIFF
.Nd Compare files and find binary differences.
.Sh SYNOPSIS
.Nm rz-diff
.B rz-diff
[\fIOPTIONS\fR]
\fIfile0\fR
\fIfile1\fR
.Sh DESCRIPTION
rz-diff compares two files or binary programs and highlight the differences between them. It supports diffing different aspects like raw bytes, text lines, functions, sections, strings, etc., based on the options used.
.Pp
.Bl -tag -width Fl
.It Fl A
Compare virtual addresses from file0 with physical addresses in file1
.It Fl a Ar [arch]	
Specify the architecture plugin to use for analysis (e.g., x86, arm)
.It Fl b Ar [bits]
Specify the register size for the chosen architecture (e.g., 16, 32, 64)
.It Fl B
Run 'aaa' when loading the binary
.It Fl C
Disable the use of colors in the output
.It Fl d Ar [algo]
Compute the edit distance between files using the chosen algorithm:
                myers | Eugene W. Myers' O(ND) algorithm (no substitution)
                leven | Levenshtein O(N^2) algorithm (with substitution)
               ssdeep | Context triggered piecewise hashing comparison
.It Fl e Ar [k=v]
Set an evaluable config variable
.It Fl H 
Enable hexadecimal visual mode for comparing files in hexadecimal format
.It Fl h
Display the help message
.It Fl i 
Use command line arguments instead of files (only for -d)
.It Fl j
Output the comparison results in JSON format
.It Fl q
Generate quiet output with minimal information
.It Fl 0 Ar [cmd]
Input for file0 when option -t 'commands' is given
.It Fl 1 Ar [cmd]
Input for file1 when option -t 'commands' is given
.It Fl S Ar [WxH]
Set the width and height of the terminal for visual mode
.It Fl t Ar [type]
Compute the difference between two files based on the specified type:
              bytes      | Compare raw bytes in the files (only for small files)
              lines      | Compare text files
              functions  | Compare functions found in the files
              classes    | Compare classes found in the files
              command    | Compare command output returned when executed in both files
                         | Require -0 <cmd>, -1 <cmd> is optional
              entries    | Compare entries found in the files
              fields     | Compare fields found in the files
              graphs     | Compare 2 functions and outputs in graphviz/dot format
                         | Require -0 <fcn name|offset>, -1 <fcn name|offset> is optional
              imports    | Compare imports found in the files
              libraries  | Compare libraries found in the files
              sections   | Compare sections found in the files
              strings    | Compare strings found in the files
              symbols    | Compare symbols found in the files
.It Fl T
Show timestamp information in the output
.It Fl V
Show version information for rz-diff
.It Fl v
be more verbose (stderr output)
.Pp 
Palette colors can be changed by adding the following lines
          inside the $HOME/.rizinrc file
  ec diff.unknown blue   | offset color
  ec diff.match   green  | match color
  ec diff.unmatch red    | mismatch color	
.Sh EXAMPLE
       Compare two binary files using the default settings:
              rz-diff file1.bin file2.bin

       Compare two text files and display the output in JSON format:
              rz-diff -j -t lines file1.txt file2.txt

       Compare two functions from an architecture plugin:
              rz-diff -t graphs -0 function1 -1 function2 binary1 binary2
.El
.Sh SEE ALSO
.Pp
.Xr rizin(1) ,
.Xr rz-find(1) ,
.Xr rz-hash(1) ,
.Xr rz-bin(1) ,
.Xr rz-asm(1) ,
.Xr rz-gg(1) ,
.Xr rz-run(1) ,
.Xr rz-ax(1) ,
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>
.It  
byteninjaa0
