.Dd March 12, 2026
.Dt RZ_ESIL 7
.Os
.Sh NAME
.Nm rz-esil
.Nd Evaluable Strings Intermediate Language
.Sh DESCRIPTION
ESIL aims to describe a Forth-like representation
for every target CPU opcode semantics.
ESIL representations can be evaluated (interpreted)
in order to emulate individual instructions.
.Sh SYNTAX
Each command of an ESIL expression is separated by a comma
.Bl -tag -width "<source0>,<source1>,<operation>"
.It Li <source0>,<source1>,<operation>
.It Li <source>,<destination>,<operation>
.It Li <source_destination>,<operation>
.El
.Sh BASIC OPERATIONS
These operations should be enough
to emulate most instructions of any architecture
.Bl -tag -width "="
.It Li =
Set the value of the destination to the value of the source
.It Li +
Add the values of source0 and source1 and push the result on the esil stack
.It Li -
Subtract the value of source0 from the value of source1
and push the result on the esil stack
.It Li *
Multiply the values of source0 and source1 and push the result on the esil stack
.It Li /
Divide the value of source1 by the value of source0
.El
.Sh BASIC OPERATIONS EXAMPLES (x86)
.Li "jmp eax -> eax,eip,="
.Sh "SEE ALSO"
.Xr rizin 1
