.Dd January 24, 2024
.Dt RZ_HASH 1
.Os
.Sh NAME
.Nm rz-hash
.Nd block based hashing utility
.Sh SYNOPSIS
.Nm rz-hash
.Op Fl vhBkjLq
.Op Fl a Ar algorithm
.Op Fl b Ar size
.Op Fl c Ar hash
.Op Fl D Ar algo
.Op Fl E Ar algo
.Op Fl s Ar string
.Op Fl x Ar hexstr
.Op Fl f Ar from
.Op Fl t Ar to
.Op Fl I Ar iv
.Op Fl S Ar seed
.Op Fl K Ar key
.Op Fl i Ar times
.Op Ar file ...
.Sh DESCRIPTION
This program is part of the Rizin project.
.Pp
.Nm rz-hash
allows you to calculate, check and show hash values of each
block of a target file.
The block size is 32768 bytes by default.
.Pp
It is possible to hash data from standard input by using
.Ql -
as the input file.
.Pp
You can compare against a known hash and retrieve the result
via the exit status.
.Pp
Large files can be hashed block by block to detect which parts
have changed.
.Pp
This command is also used internally by the
.Cm ph
command of rizin.
.Sh OPTIONS
.Bl -tag -width Fl
.It Fl v
Show version information
.It Fl h
Show usage help message
.It Fl -
Read input from standard input instead of a file
.It Fl a Ar algo
Hash algorithm; specify multiple algorithms separated by commas
(example: sha1,md4,md5,sha256)
.It Fl B
Output the calculated value for each block
.It Fl b Ar size
Set the block size
.It Fl c Ar value
Compare calculated value with the given hexadecimal hash
.It Fl e Ar endian
Set the endianness (default: big; accepted: big or little)
.It Fl D Ar algo
Decrypt the input; use
.Fl S
to set the key and
.Fl I
to set the IV if required
.It Fl E Ar algo
Encrypt the input; use
.Fl S
to set the key and
.Fl I
to set the IV if required
.It Fl f Ar from
Start calculation at the given offset
.It Fl t Ar to
Stop calculation at the given offset
.It Fl I Ar iv
Set the initialization vector
.It Fl i Ar times
Repeat the calculation N times
.It Fl j
Output results as JSON
.It Fl k
Output using OpenSSH randomkey format
.It Fl L
List all supported algorithms
.It Fl q
Quiet mode (use
.Fl qq
to output only the calculated value)
.It Fl S Ar seed
Set the seed for
.Fl a ;
use
.Ql ^
to prepend,
.Ql @
to load from file,
or
.Ql -
to read from stdin
.It Fl K Ar key
Set HMAC key or encryption key; supports
.Ql @
file and
.Ql -
stdin prefixes
.It Fl s Ar string
Read input from a zero-terminated string
.It Fl x Ar hex
Read input from a hexadecimal string
.El
.Sh DIAGNOSTICS
.Ex -std
.Pp
When
.Fl c
is used, exit status 0 indicates a hash match.
.Sh SEE ALSO
.Xr rz-asm 1 ,
.Xr rz-ax 1 ,
.Xr rz-bin 1 ,
.Xr rz-diff 1 ,
.Xr rz-find 1 ,
.Xr rz-gg 1 ,
.Xr rz-run 1
.Sh AUTHORS
.An pancake
.Aq Mt pancake@nopcode.org
.An byteninjaa0
