.Dd Jun 7, 2016
.Dt RZPM 1
.Sh NAME
.Nm RZPM
.Nd rizin package manager
.Sh SYNOPSIS
.Nm rz-pm
.Op init|update|cmd
.Op ...
.Sh DESCRIPTION
Allows to install, update, uninstall and discover plugins and tools that can be used with rizin.
.Bl -tag -width Fl
.It Fl a, Cm repo
Adds an external rz-pm repository, no arguments to -a will list all the registered repos, use '-a - repo' to unregister/remove those repos.
.It Fl I, Cm info
Show information about repository and installed packages
.It Fl i, Cm install Ar pkgname
Install a package
.It Fl gi, Cm global-install Ar pkgname
Install a package in the system directory
.It Fl t, Cm test [OK|FX|BR|XX] Cm [build-id]
Show last build + testsuite run from travis, greps for errors
.It Fl u, Cm uninstall Ar pkgname
Uninstall a package
.It Fl gu, Cm global-install Ar pkgname
Uninstall a package from the system directory
.It Fl l, Cm list
List installed packages
.It Fl s, Cm search Ar keyword
Search in database for packages matching keyword
.It Fl r, Cm run Ar command ...args
Run command with RZPM_BINDIR in PATH
.It Fl v, Cm version
Show version information
.It Fl h, Cm help
Show usage help message
.It Fl c, Cm clean
Clean the source cache
.It Fl w, Cm when
Show when a package was installed or exit 1 if pkg does not exist
.El
.Sh EXAMPLES
.Pp
Initialize and update the package database
.Pp
  $ rz-pm init
  $ rz-pm update
.Pp
Install a package
.Pp
  $ rz-pm install yara3
.Pp
Install a test package (don't git pull on $RZPM_GITDIR/yara3)
.Pp
  $ RZPM_GITSKIP=1 rz-pm install yara3
.Pp
Uninstall a package
.Pp
  $ rz-pm uninstall yara3
.Pp
Search a package
.Pp
  $ rz-pm search yara
.Pp
List available packages
.Pp
  $ rz-pm -s
.Sh SEE ALSO
.Pp
.Xr rizin(1)
