.Dd Jan 24, 2024
.Dt RZ_RUN 1
.Sh NAME
.Nm rz-run
.Nd rizin utility to run programs in exotic environments
.Sh SYNOPSIS
.Nm rz-run
.Op -v | -t | script.rr2
.Op [directives]
.Sh DESCRIPTION
This program is used as a launcher for running programs with different environments, arguments, permissions, directories, and overridden default file descriptors.
.Pp
Usage:
.Pp
.Nm rz-run -v | -t | script.rr2 [directive ..]
.Pp
.D1
program=/bin/ls
arg1=/bin
# arg2=hello
# arg3="hello\nworld"
# arg4=:048490184058104849
# arg5=:!rz-gg -p n50 -d 10:0x8048123
# arg6=@arg.txt
# arg7=@300@ABCD # 300 chars filled with ABCD pattern
# system=rizin -
# daemon=false
# aslr=no
setenv=FOO=BAR
# unsetenv=FOO
# clearenv=true
# envfile=environ.txt
timeout=3
# timeoutsig=SIGTERM # or 15
# connect=localhost:8080
# listen=8080
# pty=false
# fork=true
# bits=32
# pid=0
# pidfile=/tmp/foo.pid
# #sleep=0
# #maxfd=0
# #execve=false
# #maxproc=0
# #maxstack=0
# #core=false
# #stdio=blah.txt
# #stderr=foo.txt
stdout=foo.txt
stdin=input.txt # or !program to redirect input from another program
input=input.txt
chdir=/
chroot=/mnt/chroot
libpath=$PWD:/tmp/lib
rzpreload=yes
preload=/lib/libfoo.so
setuid=2000
seteuid=2000
setgid=2001
setegid=2001
nice=5
.D1
.Pp
The program accepts a single argument, which is the filename of the configuration file to run the program.
.Pp
It is useful when you have to run a program using long arguments or pass long data to stdin, or things like that usually required for exploiting crackmes :)
.Sh DIRECTIVES
.Pp
The rrz (rz-run) configuration file accepts the following directives, described as key=value entries and comments defined as lines starting with '#'.
.Bl -tag -width Fl
.It Ar arg[0-N]
set value for argument N passed to the program
...
.El
.Sh VALUE PREFIXES
Every value in this configuration file can contain a special
.Pp
.Bl -tag -width Fl
.It Ar @filename
Slurp contents of file and put them inside the key
...
.El
.Sh EXAMPLES
Sample rz-run script
.Pp
  $ cat foo.rrz
  #!/usr/bin/rz-run
  program=./pp400
  arg0=10
  stdin=foo.txt
  chdir=/tmp
  clearenv=true
  setenv=EGG=eggsy
  setenv=NOFUN=nogames
  unsetenv=NOFUN
  # EGG will be the only env variable
  #chroot=.
  ./foo.rrz
...
.Sh SEE ALSO
.Pp
.Xr rizin(1) ,
.Xr rz-hash(1) ,
.Xr rz-find(1) ,
.Xr rz-bin(1) ,
.Xr rz-diff(1) ,
.Xr rz-gg(1) ,
.Xr rz-asm(1) ,
.Sh AUTHORS
.Pp
Written by pancake <pancake@nopcode.org>.
.Pp
byteninjaa0.
