.Dd Jan 21, 2024
.Dt RZ_SIGN 1
.Sh NAME
.Nm RZ_SIGN
.Nd rizin signature utility
.Sh SYNOPSIS
.Nm rz-sign
.Op Fl acehoqv
.Op Fl o Ar outfile
.Ar file
.Sh DESCRIPTION
rz-sign allows to create and inspect FLIRT code signatures.
.Pp
.Bl -tag -width Fl
.It Fl a
Analyze binary after loading it with RzCore and use -AA to run aaaa instead of aaa. Available only
together with the o option.
.It Fl c
Interpret the input file as a FLIRT signature file and dump the pattern format
.It Fl e
Set an evaluable config variable. Available only together with the o option
.It Fl h
Show usage help message.
.It Fl o Ar file.sig
Perform an analysis of a binary and generate FLIRT signatures for all functions inside it
.It Fl q
Enable quiet mode.
.It Fl v
Show version information.
.El
.Sh SEE ALSO
.Pp
.Xr rizin(1) ,
.Xr rz-find(1) ,
.Xr rz-hash(1) ,
.Xr rz-bin(1) ,
.Xr rz-asm(1) ,
.Xr rz-gg(1) ,
.Xr rz-run(1) ,
.Xr rz-ax(1) ,
.Xr rz-diff(1) ,
