.Dd January 24, 2024
.Dt RZ_TEST 1
.Os
.Sh NAME
.Nm rz-test
.Nd rizin regression test suite
.Sh SYNOPSIS
.Nm rz-test
.Op Fl qvVnL
.Op Fl j Ar threads
.Op Ar test | @test-type
.Sh DESCRIPTION
This command runs rizin regression tests.
.Pp
Tests are selected by name or type.
.Sh OPTIONS
.Bl -tag -width Fl
.It Fl h
Show usage help
.It Fl v
Show version information
.It Fl q
Quiet mode
.It Fl V
Verbose output
.It Fl n
Do not execute tests
.It Fl L
Log mode for CI
.It Fl j Ar threads
Number of concurrent threads
.It Fl r Ar rizin
Path to rizin executable
.It Fl m Ar rz-asm
Path to rz-asm executable
.It Fl t Ar seconds
Timeout per test
.It Fl o Ar file
Write JSON output
.El
.Sh ENVIRONMENT
.Bl -tag -width EDITOR
.It Ev EDITOR
Editor to use
.El
.Sh USAGE
Load tests without executing:
.Pp
.Dl $ rz-test -n
.Sh SEE ALSO
.Xr rz-asm 1 ,
.Xr rz-ax 1 ,
.Xr rz-bin 1 ,
.Xr rz-diff 1 ,
.Xr rz-find 1 ,
.Xr rz-gg 1 ,
.Xr rz-hash 1 ,
.Xr rz-run 1
.Sh AUTHORS
.An pancake
.Aq Mt pancake@nopcode.org
.An byteninjaa0
