labels:
  platform: darwin/arm64

steps:
  build:
    image: /bin/bash
    commands:
      - meson build --prefix="`pwd`/prefix"
      - ninja -C build
      - ninja -C build install
  fetch-testbins:
    image: /bin/bash
    commands:
      - cd test
      - git clone --depth=1 https://github.com/rizinorg/rizin-testbins bins
  install-rzpipe:
    image: /bin/bash
    commands:
      - cd test
      - git clone --depth=1 https://github.com/rizinorg/rz-pipe
      - pip3 install --user "file://`pwd`/rz-pipe#egg=rzpipe&subdirectory=python"
  pre-test:
    image: /bin/bash
    commands:
      - ipcs -s
  unit-test:
    image: /bin/bash
    commands:
      - ninja -C build test
  rz-test:
    image: /bin/bash
    commands:
      - export PATH="`pwd`/prefix/bin:$PATH"
      - cd test
      - rz-test -L
  post-test:
    image: /bin/bash
    commands:
      - ipcs -s
