platform: darwin/arm64

pipeline:
  build:
    image: /bin/bash
    commands:
      - meson build --prefix="`pwd`/prefix"
      - ninja -C build
      - ninja -C build install
  fetch-testbins:
    image: /bin/bash
    commands:
      - cd test
      - make bins
  unit-test:
    image: /bin/bash
    commands:
      - ninja -C build test
  rz-test:
    image: /bin/bash
    commands:
      - export PATH="`pwd`/prefix/bin:$PATH"
      - cd test
      - rz-test -L
