name: "Pull Request Labeler"
on:
- pull_request_target

# Automatically cancel any previous workflow on new push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  
