name: Muon build

on:
  push:
    paths:
    - '**.c'
    - '**.h'
    - '**.in'
    - '**.inc'
    - '**/meson.build'
    - 'subprojects/**'
    - 'test/**'
    - '.github/workflows/muon.yml'
    branches:
    - 'dev'
    - 'stable'
    - 'container-*'
  pull_request:
    paths:
    - '**.c'
    - '**.h'
    - '**.in'
    - '**.inc'
    - '**/meson.build'
    - 'subprojects/**'
    - 'test/**'
    - '.github/workflows/muon.yml'
    branches:
    - 'dev'
    - 'stable'
    - 'release-*'

jobs:
  build:
    name: ubuntu-muon
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt-get --assume-yes update
          sudo apt-get --assume-yes install python3-wheel python3-setuptools pkgconf libcurl4-openssl-dev libpkgconf-dev libarchive-dev
          sudo python3 -m pip install ninja

    - name: Checkout Muon repository
      run: |
          git clone https://git.sr.ht/~lattis/muon

    - name: Compiling and installing Muon
      working-directory: muon
      run: |
          ./bootstrap.sh build
          build/muon setup build
          ninja -C build
          sudo cp build/muon /usr/bin/muon

    - name: Muon setup
      run: muon setup build
    - name: Ninja compile and install
      run: ninja -C build && sudo muon -C build install

    - name: Checkout our Testsuite Binaries
      uses: actions/checkout@v3
      with:
          repository: rizinorg/rizin-testbins
          path: test/bins

    - name: Run unit tests
      run: muon -C build test
    - name: Rizin version
      run: |
        rizin -v
